function [BeginTimes, EndTimes, LowFreqHz, HighFreqHz, DeltaTimes, DeltaFreqHz] = importRavenBox(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [BEGINTIMES, ENDTIMES, LOWFREQHZ, HIGHFREQHZ, DELTATIMES,
%  DELTAFREQHZ] = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [BEGINTIMES, ENDTIMES, LOWFREQHZ, HIGHFREQHZ, DELTATIMES,
%  DELTAFREQHZ] = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  [BeginTimes, EndTimes, LowFreqHz, HighFreqHz, DeltaTimes, DeltaFreqHz] = importfile("G:\My Drive\Ole Miss\NCCHE\DeepWaves\TN\wlog1\Selections_cleaned\WLOG1_190421_0000.Table.1.selections.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 04-Dec-2019 14:50:03

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "BeginTimes", "EndTimes", "LowFreqHz", "HighFreqHz", "DeltaTimes", "DeltaFreqHz", "Var10", "Var11"];
opts.SelectedVariableNames = ["BeginTimes", "EndTimes", "LowFreqHz", "HighFreqHz", "DeltaTimes", "DeltaFreqHz"];
opts.VariableTypes = ["string", "string", "string", "double", "double", "double", "double", "double", "double", "string", "string"];
opts = setvaropts(opts, [1, 2, 3, 10, 11], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 2, 3, 10, 11], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
BeginTimes = tbl.BeginTimes;
EndTimes = tbl.EndTimes;
LowFreqHz = tbl.LowFreqHz;
HighFreqHz = tbl.HighFreqHz;
DeltaTimes = tbl.DeltaTimes;
DeltaFreqHz = tbl.DeltaFreqHz;
end